language: python

jobs:
  include:
    - stage: sync-images
      script: make update-images
      deploy:
        provider: pages
        skip-cleanup: true
        target-branch: master
        github-token: $GH_TOKEN
        keep-history: true
        verbose: true
        on:
          branch: master
    #- stage: promote-stable
    #  script: make promote-stable-job

stages:
  - sync-images
  - promote-stable
