apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-release-stable-images
  namespace: hive
  annotations:
    apps.open-cluster-management.io/github-path: clusterImageSets
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: ocp-clusterimagesets/openshift-release-dev-images
  placement:
   local: true
