apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-release-candidate-images
  namespace: hive
  labels:
    subscription-pause: "false"
  annotations:
    apps.open-cluster-management.io/github-path: clusterImageSets/releases
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: ocp-clusterimagesets/openshift-release-dev-images
  placement:
   local: true
