apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'true'
  name: img4.5.0-0.hotfix-2020-08-24-185832-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.5.0-0.hotfix-2020-08-24-185832-x86_64
